# Generated by Django 4.2.30 on 2026-05-28 06:52

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('tipo', models.CharField(choices=[('aluno', 'Aluno'), ('coordenador', 'Coordenador'), ('supervisor_empresa', 'Supervisor de Empresa')], default='aluno', max_length=20)),
                ('nome', models.CharField(max_length=100)),
                ('email_institucional', models.EmailField(blank=True, default='', max_length=254)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('rg', models.CharField(blank=True, default='', max_length=20)),
                ('coeficiente_rendimento', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('matriculado_estagio', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
            },
        ),
        migrations.CreateModel(
            name='Coordenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(max_length=100)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coordenador', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Coordenador',
                'verbose_name_plural': 'Coordenadores',
            },
        ),
        migrations.CreateModel(
            name='EmpresaConcedente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('razao_social', models.CharField(max_length=200)),
                ('areas_atuacao', models.TextField()),
                ('localizacao', models.CharField(max_length=300)),
                ('email_contato', models.EmailField(max_length=254)),
                ('aprovada_ibmec', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Empresa Concedente',
                'verbose_name_plural': 'Empresas Concedentes',
            },
        ),
        migrations.CreateModel(
            name='SupervisorEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(blank=True, default='', max_length=100)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisores', to='app.empresaconcedente')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_empresa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Supervisor de Empresa',
                'verbose_name_plural': 'Supervisores de Empresa',
            },
        ),
        migrations.CreateModel(
            name='ProcessoEstagio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado'), ('CORRECAO_SOLICITADA', 'Correção Solicitada'), ('ATIVO', 'Ativo'), ('ENCERRADO', 'Encerrado'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=30)),
                ('horas_semanais', models.PositiveIntegerField()),
                ('data_inicio_prevista', models.DateField()),
                ('data_fim_prevista', models.DateField()),
                ('plano_atividades', models.TextField()),
                ('justificativa_rejeicao', models.TextField(blank=True, default='')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processos', to='app.aluno')),
                ('coordenador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos', to='app.coordenador')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processos', to='app.empresaconcedente')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos', to='app.supervisorempresa')),
            ],
            options={
                'verbose_name': 'Processo de Estágio',
                'verbose_name_plural': 'Processos de Estágio',
            },
        ),
        migrations.CreateModel(
            name='DocumentoProcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('TCE', 'Termo de Compromisso de Estágio'), ('APOLICE', 'Apólice de Seguro'), ('RELATORIO_PARCIAL', 'Relatório Parcial'), ('RELATORIO_FINAL', 'Relatório Final'), ('AVALIACAO_EMPRESA', 'Avaliação da Empresa'), ('TERMO_REALIZACAO', 'Termo de Realização'), ('OUTRO', 'Outro')], max_length=30)),
                ('arquivo', models.FileField(upload_to='documentos/')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado')], default='PENDENTE', max_length=20)),
                ('versao', models.PositiveIntegerField(default=1)),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_enviados', to=settings.AUTH_USER_MODEL)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='app.processoestagio')),
            ],
            options={
                'verbose_name': 'Documento de Processo',
                'verbose_name_plural': 'Documentos de Processo',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('carga_horaria_minima_total', models.PositiveIntegerField(default=0, help_text='Carga horária mínima total exigida para integralização (horas)')),
                ('carga_horaria_maxima_diaria', models.PositiveIntegerField(default=6, help_text='Limite diário de horas permitido pela legislação/PPC')),
                ('coordenador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos_coordenados', to='app.coordenador', verbose_name='Coordenador responsável')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.AddField(
            model_name='aluno',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alunos', to='app.curso'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aluno', to=settings.AUTH_USER_MODEL),
        ),
    ]
