# Generated by Django 4.2.30 on 2026-05-31 01:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresaconcedente',
            name='descricao',
            field=models.TextField(blank=True, help_text='Descrição da empresa, estrutura organizacional e principais atividades'),
        ),
        migrations.AddField(
            model_name='processoestagio',
            name='data_fim_real',
            field=models.DateField(blank=True, help_text='Data real de término do estágio', null=True),
        ),
        migrations.AddField(
            model_name='processoestagio',
            name='data_inicio_real',
            field=models.DateField(blank=True, help_text='Data real de início do estágio', null=True),
        ),
        migrations.AddField(
            model_name='processoestagio',
            name='numero_seguro',
            field=models.CharField(blank=True, help_text='Número da apólice de seguro contra acidentes pessoais', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='processoestagio',
            name='professor_orientador',
            field=models.ForeignKey(blank=True, help_text='Professor orientador do estágio pela instituição de ensino', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos_orientados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='processoestagio',
            name='valor_bolsa',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor da bolsa mensal (obrigatório para estágio não obrigatório)', max_digits=10, null=True),
        ),
    ]
