# Generated by Django 4.2.30 on 2026-05-21 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='carga_horaria_maxima_diaria',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='carga_horaria_minima_total',
        ),
        migrations.AlterField(
            model_name='aluno',
            name='coeficiente_rendimento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='coordenador',
            name='departamento',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='aprovada_ibmec',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='areas_atuacao',
            field=models.TextField(),
        ),
    ]
