# Generated by Django 4.2.30 on 2026-06-03 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('aluno', 'Aluno'), ('coordenador', 'Coordenador'), ('empresa', 'Empresa')], default='aluno', max_length=20),
        ),
    ]
