# Generated by Django 4.2.30 on 2026-05-31 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_empresaconcedente_descricao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processoestagio',
            name='valor_auxilio_transporte',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor do auxílio transporte mensal (obrigatório para estágio não obrigatório)', max_digits=10, null=True),
        ),
    ]
