# Generated by Django 4.2.30 on 2026-05-31 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_coordenador_departamento_opcional'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='matriculado_estagio',
            field=models.BooleanField(default=False, help_text='Indica se o aluno está formalmente matriculado em estágio'),
        ),
        migrations.AddField(
            model_name='curso',
            name='carga_horaria_maxima_diaria',
            field=models.PositiveIntegerField(blank=True, help_text='Limite diário de horas permitido pela legislação/PPC', null=True),
        ),
        migrations.AlterField(
            model_name='solicitacaoestagio',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado'), ('RETIFICACAO_SOLICITADA', 'Retificação Solicitada'), ('ATIVO', 'Ativo'), ('ENCERRADO', 'Encerrado'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=30),
        ),
    ]
