# Generated by Django 4.2.30 on 2026-05-31 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_processoestagio_valor_auxilio_transporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresaconcedente',
            name='responsavel_legal_cargo',
            field=models.CharField(blank=True, help_text='Cargo do responsável legal', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empresaconcedente',
            name='responsavel_legal_nome',
            field=models.CharField(blank=True, help_text='Nome do responsável legal da empresa (quem assina o TCE)', max_length=200, null=True),
        ),
    ]
