# Generated by Django 4.2.30 on 2026-05-31 05:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_empresaconcedente_responsavel_legal_cargo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoprocesso',
            name='observacoes',
            field=models.TextField(blank=True, help_text='Observações/parecer do coordenador ao validar o documento', null=True),
        ),
        migrations.AddField(
            model_name='documentoprocesso',
            name='score_conformidade',
            field=models.FloatField(default=0.0, help_text='Score automático de conformidade (0.0 a 1.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='coordenador',
            name='departamento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='LogDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('UPLOAD', 'Upload'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado'), ('EDITADO', 'Editado'), ('GERADO', 'Gerado pelo sistema')], max_length=20)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='app.documentoprocesso')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Documento',
                'verbose_name_plural': 'Logs de Documentos',
                'ordering': ['-data'],
            },
        ),
    ]
