# Generated by Django 4.2.30 on 2026-06-03 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_documentoprocesso_observacoes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processoestagio',
            name='respostas_formulario',
            field=models.JSONField(blank=True, help_text='Respostas do aluno ao formulário de avaliação', null=True),
        ),
        migrations.CreateModel(
            name='ModeloFormulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('secoes', models.JSONField(default=list, help_text='Lista de seções do formulário. Tipos válidos: auto, checkbox_duplo, escala_3, escala_1_4_multi, escala_1_4, texto_livre.')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.coordenador')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelos_formulario', to='app.curso')),
            ],
            options={
                'verbose_name': 'Modelo de Formulário',
                'verbose_name_plural': 'Modelos de Formulário',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='processoestagio',
            name='modelo_formulario',
            field=models.ForeignKey(blank=True, help_text='Modelo de formulário de avaliação atribuído a este processo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos', to='app.modeloformulario'),
        ),
    ]
