# Generated by Django 4.2.30 on 2026-06-06 03:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_processoestagio_respostas_formulario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='periodo_atual',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Período acadêmico atual do aluno (1 a 12)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
    ]
