# Generated by Django 4.2.30 on 2026-06-07 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_aluno_periodo_atual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='coeficiente_rendimento',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Coeficiente de rendimento do aluno (ex: 8.50)', max_digits=4),
        ),
    ]
