# Generated by Django 4.2.30 on 2026-06-09 22:55

from django.db import migrations


def populate_coordenadores_cursos(apps, schema_editor):
    """Popula coordenadores e cursos com dados iniciais."""
    Usuario = apps.get_model('app', 'Usuario')
    Coordenador = apps.get_model('app', 'Coordenador')
    Curso = apps.get_model('app', 'Curso')

    # Dados dos coordenadores
    coordenadores_data = {
        'talita': ('Profª. Talita de Oliveira Trindade', 'talita@ibmec.edu.br'),
        'gustavo': ('Prof. Gustavo Herkenhoff Moreira', 'gustavo@ibmec.edu.br'),
        'michele': ('Profª. Michele Pedrosa Paumgartten', 'michele@ibmec.edu.br'),
        'victor': ('Prof. Victor Azevedo', 'victor@ibmec.edu.br'),
        'renato': ('Prof. Renato Salgado Mendes', 'renato@ibmec.edu.br'),
        'ticianne': ('Profª. Ticianne Ribeiro de Souza', 'ticianne@ibmec.edu.br'),
        'clayton': ('Prof. Clayton Jones Alves da Silva', 'clayton@ibmec.edu.br'),
        'thiago': ('Prof. Thiago Silva de Souza', 'thiago@ibmec.edu.br'),
    }

    # Criar usuários e coordenadores
    coords = {}
    for username, (nome_completo, email) in coordenadores_data.items():
        user, _ = Usuario.objects.get_or_create(
            username=username,
            defaults={
                'password': 'placeholder',
                'tipo': 'coordenador',
                'nome': nome_completo,
                'email_institucional': email,
            }
        )
        coord, _ = Coordenador.objects.get_or_create(usuario=user)
        coords[username] = coord

    # Criar cursos
    cursos_data = [
        ('Administração', 'talita'),
        ('Ciências Contábeis', 'talita'),
        ('Ciências Econômicas', 'gustavo'),
        ('Direito', 'michele'),
        ('Comunicação Social - Publicidade e Propaganda', 'victor'),
        ('Relações Internacionais', 'renato'),
        ('Arquitetura e Urbanismo', 'ticianne'),
        ('Engenharia Civil', 'clayton'),
        ('Engenharia de Computação', 'clayton'),
        ('Engenharia Mecânica', 'clayton'),
        ('Engenharia de Produção', 'clayton'),
        ('Ciência de Dados e Inteligência Artificial', 'thiago'),
        ('Análise e Desenvolvimento de Sistemas', 'thiago'),
    ]

    for nome_curso, coord_username in cursos_data:
        Curso.objects.get_or_create(
            nome=nome_curso,
            defaults={
                'coordenador': coords[coord_username],
                'carga_horaria_minima_total': 400,
                'carga_horaria_maxima_diaria': 6,
            }
        )


def reverse_populate(apps, schema_editor):
    """Desfaz a população (não remove dados para segurança)."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_template_documento'),
    ]

    operations = [
        migrations.RunPython(populate_coordenadores_cursos, reverse_populate),
    ]
