# Generated by Django 4.2.30 on 2026-06-10 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_populate_coordenadores_cursos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='coordenador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos', to='app.coordenador', verbose_name='Coordenador responsável'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email_institucional',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
