# Generated by Django 4.2.30 on 2026-06-11 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_documentoprocesso_titulo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacaoempresa',
            name='aluno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avaliacoes_empresas', to='app.aluno'),
        ),
        migrations.AlterField(
            model_name='avaliacaoempresa',
            name='processo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avaliacao_empresa', to='app.processoestagio'),
        ),
    ]
